version: '3.7'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    image: dpnetca/django_docker_prod
    command: gunicorn django_docker.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    expose:
      - 8000
    env_file: secret.env
    depends_on:
      - db
  db:
    image: postgres:11.5-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file: secret.env.db
  web:
    build: ./nginx
    image: dpnetca/django_docker_prod_web
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - 8080:80
    depends_on:
      - app
  
volumes:
  postgres_data_prod:
  static_volume:
  media_volume:
