# Generated by Django 2.2.4 on 2019-08-15 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpleforms', '0002_getanimal_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleforms.Executive')),
            ],
        ),
        migrations.AddField(
            model_name='executive',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='simpleforms.Organization'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleforms.Manager')),
            ],
        ),
    ]
